### ISSUE TITLE
ImportError when importing ncclient.transport

### ISSUE THREAD

**Issue by diagonalfish** [ncclient/ncclient#169]
In ncclient 0.5.3, importing the ncclient.transport module results in an exception:
```
>>> import ncclient.transport
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/usr/lib/python2.7/site-packages/ncclient/transport/__init__.py", line 17, in <module>
    from ncclient.transport.session import Session, SessionListener
  File "/usr/lib/python2.7/site-packages/ncclient/transport/session.py", line 28, in <module>
    from ncclient.operations.notify import Notification
  File "/usr/lib/python2.7/site-packages/ncclient/operations/__init__.py", line 16, in <module>
    from ncclient.operations.rpc import RPC, RPCReply, RPCError, RaiseMode
  File "/usr/lib/python2.7/site-packages/ncclient/operations/rpc.py", line 20, in <module>
    from ncclient.transport import SessionListener
ImportError: cannot import name SessionListener
```

I have verified that this works fine in 0.5.2.

**Comment by jwwilcox** [comment]
Looks like there's an import-cycle there.

As at least a temporary workaround, you can do this:

    Python 2.7.6 (default, Oct 26 2016, 20:30:19) 
    [GCC 4.8.4] on linux2
    Type "help", "copyright", "credits" or "license" for more information.
    >>> import ncclient.operations
    >>> import ncclient.transport
    >>>

**Comment by jwwilcox** [comment]
The cycle seems to have closed when adding support for notifications. I can investigate a true fix.

**Comment by leopoul** [comment]
Have merged adamcubel's PR. Will have a new release tomorrow.

Thanks!
Leo

**Comment by last-partizan** [comment]
@leopoul hey, looks like you forgot to release?
