### ISSUE TITLE
Failing issue in using ncclient in windows

### ISSUE THREAD

**Issue by dineshbaburam91** [ncclient/ncclient#597]
I am facing an issue in importing ncclient in Windows with the latest release 0.6.16

```
  File "C:\hostedtoolcache\windows\Python\3.10.11\x64\lib\site-packages\ncclient\manager.py", line 21, in <module>
    from ncclient import operations
  File "C:\hostedtoolcache\windows\Python\3.10.11\x64\lib\site-packages\ncclient\operations\__init__.py", line 16, in <module>
    from ncclient.operations.rpc import RPC, RPCReply, RPCError, RaiseMode, GenericRPC
  File "C:\hostedtoolcache\windows\Python\3.10.11\x64\lib\site-packages\ncclient\operations\rpc.py", line 20, in <module>
    from ncclient.transport import SessionListener
  File "C:\hostedtoolcache\windows\Python\3.10.11\x64\lib\site-packages\ncclient\transport\__init__.py", line 20, in <module>
    from ncclient.transport.unixSocket import UnixSocketSession
  File "C:\hostedtoolcache\windows\Python\3.10.11\x64\lib\site-packages\ncclient\transport\unixSocket.py", line 18, in <module>
    from socket import AF_UNIX, SOCK_STREAM
ImportError: cannot import name 'AF_UNIX' from 'socket' (C:\hostedtoolcache\windows\Python\3.10.11\x64\lib\socket.py)
```

**Comment by SunsetOrange** [comment]
Confirming Exception on Windows 11 Pro 23H2 and Python 3.12.5 with ncclient 0.6.16. Works fine with 0.6.15.

**Comment by ubaumann** [comment]
The new release 0.6.16 (9 Oct 2024) containers #591. This PR introduces the issue.
It would be nice to be able to keep the Windows support. 

https://github.com/ncclient/ncclient/blob/652ef67b266df0ee02bbbbc4cc6eb09ca01f4878/ncclient/transport/__init__.py#L20

https://github.com/ncclient/ncclient/blob/652ef67b266df0ee02bbbbc4cc6eb09ca01f4878/ncclient/transport/unixSocket.py#L18
